"""커뮤니티관련기능추가

Revision ID: 1d9905d4509f
Revises: d4e5f6a7b8c9
Create Date: 2026-08-14 11:42:43.815683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d9905d4509f'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'reply_id')
    )
    op.drop_index(op.f('ix_recommendations_user_rank'), table_name='recommendations')
    op.add_column('replies', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('replies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('replies', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'replies', 'replies', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.alter_column('replies', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('replies', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('replies', 'parent_id')
    op.create_index(op.f('ix_recommendations_user_rank'), 'recommendations', ['user_id', 'rank'], unique=False)
    op.drop_table('reply_likes')
    # ### end Alembic commands ###
