"""final_schema_init

Revision ID: 657f8c0622bc
Revises: 6ff01703b3b7
Create Date: 2026-05-01 04:32:01.480255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657f8c0622bc'
down_revision: Union[str, Sequence[str], None] = '6ff01703b3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_id'), 'people', ['id'], unique=False)
    op.create_index(op.f('ix_people_tmdb_id'), 'people', ['tmdb_id'], unique=True)
    op.create_table('movie_directors',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'director_id')
    )
    op.execute("DROP TABLE actors CASCADE")
    op.add_column('genres', sa.Column('name_ko', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'genres', ['name_ko'])
    op.add_column('keywords', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_keywords_tmdb_id'), 'keywords', ['tmdb_id'], unique=True)
    op.add_column('movie_actors', sa.Column('cast_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'movie_actors', 'people', ['actor_id'], ['id'], ondelete='CASCADE')
    op.add_column('movies', sa.Column('title_ko', sa.String(length=255), nullable=True))
    op.drop_column('movies', 'director')
    op.add_column('otts', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.add_column('otts', sa.Column('name_ko', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_otts_tmdb_id'), 'otts', ['tmdb_id'], unique=True)
    op.create_unique_constraint(None, 'otts', ['name_ko'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otts', type_='unique')
    op.drop_index(op.f('ix_otts_tmdb_id'), table_name='otts')
    op.drop_column('otts', 'name_ko')
    op.drop_column('otts', 'tmdb_id')
    op.add_column('movies', sa.Column('director', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'title_ko')
    op.drop_constraint(None, 'movie_actors', type_='foreignkey')
    op.create_foreign_key(op.f('movie_actors_actor_id_fkey'), 'movie_actors', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('movie_actors', 'cast_name')
    op.drop_index(op.f('ix_keywords_tmdb_id'), table_name='keywords')
    op.drop_column('keywords', 'tmdb_id')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_column('genres', 'name_ko')
    op.create_table('actors',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('actors_pkey'))
    )
    op.create_index(op.f('ix_actors_id'), 'actors', ['id'], unique=False)
    op.drop_table('movie_directors')
    op.drop_index(op.f('ix_people_tmdb_id'), table_name='people')
    op.drop_index(op.f('ix_people_id'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
