"""(CREATE) : movie_ott

Revision ID: 6ff01703b3b7
Revises: fdb4e9267dc3
Create Date: 2026-04-10 04:04:01.630708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff01703b3b7'
down_revision: Union[str, Sequence[str], None] = 'fdb4e9267dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_column('genres', 'tmdb_id')
    # ### end Alembic commands ###
