"""영화신고movie_id추가

Revision ID: 7937916adf23
Revises: 938de868a0cd
Create Date: 2026-08-22 13:10:11.878090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7937916adf23'
down_revision: Union[str, Sequence[str], None] = '938de868a0cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'movie_id')
    # ### end Alembic commands ###
