"""add interaction timestamps

Revision ID: ca47ba289c35
Revises: b5528930c58d
Create Date: 2026-05-18 03:43:45.425069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca47ba289c35'
down_revision: Union[str, Sequence[str], None] = 'b5528930c58d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('pinned_at', sa.DateTime(), nullable=True))
    op.add_column('user_interactions', sa.Column('watched_at', sa.DateTime(), nullable=True))
    op.add_column('user_interactions', sa.Column('passed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_interactions', 'passed_at')
    op.drop_column('user_interactions', 'watched_at')
    op.drop_column('user_interactions', 'pinned_at')
    # ### end Alembic commands ###
