ENGINE_NAME = "v3"
ENGINE_VERSION = "v3.0.0"
SERVING_BUNDLE_FORMAT_VERSION = 1
SERVING_BUNDLE_ROOT = "assets/ml_models/v3"
POLICY_CONFIG_VERSION = "v3-policy-quality-v1"

CANDIDATE_POOL_SIZE = 100
CANDIDATE_RESERVE_SIZE = 50
CANDIDATE_STORAGE_SIZE = CANDIDATE_POOL_SIZE + CANDIDATE_RESERVE_SIZE
INITIAL_CANDIDATE_SCAN_SIZE = CANDIDATE_STORAGE_SIZE * 20
INITIAL_CANDIDATE_FILTER_POLICY_VERSION = "catalog-qualification-v1"
MAX_PAGE_SIZE = 100
CANDIDATE_USER_BLOCK_SIZE = 32
CANDIDATE_ITEM_BLOCK_SIZE = 8_192
CANDIDATE_CHECKPOINT_USER_COUNT = 1_024
CANDIDATE_MATERIALIZATION_WORKER_COUNT = 1
CANDIDATE_SNAPSHOT_FORMAT_VERSION = 1
LIGHTFM_CANDIDATE_SCORE_POLICY_VERSION = "identity-confidence-v1"
SHORT_TERM_RETRIEVAL_LIMIT = 100
SHORT_TERM_CANDIDATE_CACHE_FORMAT_VERSION = 3
SHORT_TERM_CANDIDATE_CACHE_TTL_SECONDS = 60 * 60 * 6
SHORT_TERM_CANDIDATE_CACHE_TTL_JITTER_SECONDS = 60 * 30
SHORT_TERM_COLLECTION_WINDOW_SECONDS = 60 * 60 * 24
SHORT_TERM_DEBOUNCE_SECONDS = 30.0
SHORT_TERM_MAX_WAIT_SECONDS = 120.0
SHORT_TERM_MIN_DISTINCT_POSITIVE_MOVIES = 3
SHORT_TERM_STRONG_MIN_DISTINCT_MOVIES = 2
SHORT_TERM_STRONG_MIN_WEIGHT = 2.0
SHORT_TERM_DRIFT_MAX_WEIGHT = 0.45
SHORT_TERM_CONTEXT_FLOOR_MIN_DRIFT = 0.60
SHORT_TERM_CONTEXT_FLOOR_MAX_RATIO = 0.25
LONG_TERM_ONTOLOGY_RETRIEVAL_LIMIT = 100
LONG_TERM_MODEL_SELECTION_WEIGHT = 0.65
LONG_TERM_MODEL_MIN_SELECTION_WEIGHT = 0.55
LONG_TERM_ONTOLOGY_SELECTION_WEIGHT = 0.35
LONG_TERM_ONTOLOGY_MIN_RATIO = 0.20
LONG_TERM_SEMANTIC_AGREEMENT_TOP_K = 50
# Collaborative confidence stays conservative during bootstrap. Full model
# influence requires both a varied population and enough evidence for the user.
COLLABORATIVE_POPULATION_MIN_USERS = 50
COLLABORATIVE_POPULATION_FULL_USERS = 500
COLLABORATIVE_USER_MIN_POSITIVE_PAIRS = 3
COLLABORATIVE_USER_FULL_POSITIVE_PAIRS = 20
COLLABORATIVE_INPUT_MAX_SUPPORT_GOOD = 0.25
COLLABORATIVE_INPUT_MAX_SUPPORT_BAD = 0.75
COLLABORATIVE_CANDIDATE_JACCARD_GOOD = 0.20
COLLABORATIVE_CANDIDATE_JACCARD_BAD = 0.75

# Phase C preference-shift detection. Primary semantic families determine whether
# a recent interest is materially different; entity-heavy families are supporting evidence.
PREFERENCE_SHIFT_MIN_HISTORICAL_MOVIES = 5
PREFERENCE_SHIFT_DRIFT_DISTANCE_THRESHOLD = 0.70
PREFERENCE_SHIFT_DISTANCE_NOISE_FLOOR = 0.35
PREFERENCE_SHIFT_PRIMARY_FAMILY_WEIGHTS = {
    "genre": 0.60,
    "theme": 0.25,
    "mood": 0.15,
}
PREFERENCE_SHIFT_SECONDARY_FAMILY_WEIGHTS = {
    "keyword": 0.50,
    "actor": 0.30,
    "director": 0.20,
}
PREFERENCE_SHIFT_PRIMARY_GROUP_WEIGHT = 0.85
PREFERENCE_SHIFT_SECONDARY_ONLY_CAP = 0.35

# S8 serving policy defaults. These values are provisional and must be tuned by ablation.
POLICY_PERSONAL_COMPONENT_WEIGHT = 0.75
POLICY_ONTOLOGY_COMPONENT_WEIGHT = 0.25
POLICY_ONTOLOGY_SHORT_TERM_MULTIPLIER = 0.5
POLICY_BLOCKED_MOVIE_STATUSES = frozenset({"취소됨", "Canceled"})
POLICY_OTT_BONUS_MAX = 0.04
POLICY_RECENCY_BONUS_MAX = 0.03
POLICY_RECENCY_WINDOW_DAYS = 365
POLICY_QUALITY_BONUS_MAX = 0.08
POLICY_QUALITY_VOTE_CONFIDENCE_PRIOR = 100.0
POLICY_QUALITY_POPULARITY_REFERENCE = 100.0
POLICY_CATALOG_TRUST_PENALTY_MAX = 0.05
POLICY_CATALOG_TRUST_VOTE_THRESHOLD = 20
LONG_TERM_COLD_ITEM_GRACE_DAYS = 180
LONG_TERM_MATURE_COLD_ITEM_MIN_VOTE_COUNT = POLICY_CATALOG_TRUST_VOTE_THRESHOLD
POLICY_NEGATIVE_MAX_BASE_RATIO = 0.30
POLICY_NEGATIVE_MAX_ABSOLUTE = 0.20
POLICY_NEGATIVE_CONFIDENCE_PAIR_COUNT = 3
POLICY_NEGATIVE_SHORT_TERM_MULTIPLIER = 1.25
POLICY_NEGATIVE_FEATURE_WEIGHTS = {
    "genre": 0.15,
    "keyword": 0.35,
    "actor": 0.30,
    "director": 0.45,
    "theme": 0.45,
    "mood": 0.35,
}
POLICY_MMR_SIMILARITY_PENALTY_MAX = 0.08
POLICY_REPETITION_PENALTY_MAX = 0.06
POLICY_SHORT_TERM_MIN_RATIO = 0.15
POLICY_SHORT_TERM_MAX_RATIO = 0.40
COLD_START_FEATURE_ONLY_MODEL_WEIGHT = 0.30
COLD_START_GENRE_ONLY_MODEL_WEIGHT = 0.15
COLD_START_OVERVIEW_SUPPORT_BONUS_MAX = 0.25
COLD_START_GENRE_ONLY_SEMANTIC_WEIGHT = 0.65
COLD_START_GENRE_ONLY_QUALITY_WEIGHT = 0.35
COLD_START_GENRE_COVERAGE_WEIGHT = 0.70
COLD_START_GENRE_SPECIFICITY_WEIGHT = 0.30
COLD_START_GENRE_ONLY_MIN_VOTE_COUNT = 1
COLD_START_GENRE_ONLY_TRUSTED_VOTE_COUNT = 20

ONTOLOGY_BUILD_BATCH_SIZE = 1_000
ONTOLOGY_BUILD_WORKER_COUNT = 4
ONTOLOGY_AGGREGATION_POLICY_VERSION = "bounded-union-v1"
ONTOLOGY_BUILD_WORK_MEM = "64MB"

ITEM_FEATURE_EXPORTER_VERSION = "v1"
USER_FEATURE_EXPORTER_VERSION = "v2"
USER_FEATURE_EXPLICIT_GENRE_WEIGHT = 1.0
USER_FEATURE_FAVORITE_DERIVED_WEIGHT = 0.5
USER_FEATURE_LONG_TERM_DERIVED_WEIGHT = 1.0
ITEM_FEATURE_MIN_MOVIE_FREQUENCY = {
    "keyword": 5,
    "actor": 5,
    "director": 5,
}
ITEM_FEATURE_MAX_CATALOG_RATIO = {
    "keyword": 0.5,
}

LIGHTFM_IDENTITY_NO_COMPONENTS = 64
LIGHTFM_IDENTITY_LOSS = "warp"
LIGHTFM_IDENTITY_EPOCHS = 40
LIGHTFM_IDENTITY_LEARNING_RATE = 0.05
LIGHTFM_IDENTITY_USER_ALPHA = 1e-6
LIGHTFM_IDENTITY_ITEM_ALPHA = 1e-6
LIGHTFM_IDENTITY_MAX_SAMPLED = 10
LIGHTFM_IDENTITY_RANDOM_SEED = 42
LIGHTFM_IDENTITY_NUM_THREADS = 1

LIGHTFM_HYBRID_NO_COMPONENTS = 32
LIGHTFM_HYBRID_EPOCHS = 20
LIGHTFM_HYBRID_LEARNING_RATE = 0.01
LIGHTFM_HYBRID_USER_ALPHA = 1e-5
LIGHTFM_HYBRID_ITEM_ALPHA = 1e-5
LIGHTFM_HYBRID_MAX_SAMPLED = 10
LIGHTFM_HYBRID_NUM_THREADS = 1
LIGHTFM_HYBRID_FEATURE_REPRESENTATION = "supported_identity_field_budgeted"
LIGHTFM_HYBRID_USER_IDENTITY_WEIGHT = 2.0
LIGHTFM_HYBRID_USER_SEMANTIC_WEIGHT = 0.5
LIGHTFM_HYBRID_ITEM_IDENTITY_WEIGHT = 1.0
LIGHTFM_HYBRID_ITEM_SEMANTIC_WEIGHT = 1.0
LIGHTFM_HYBRID_ITEM_FIELD_BUDGETS = {
    "genre": 0.25,
    "keyword": 0.20,
    "actor": 0.15,
    "director": 0.15,
    "theme": 0.15,
    "mood": 0.10,
}
LIGHTFM_HYBRID_ITEM_KEYWORD_WEIGHTING = "normalized_idf"
LIGHTFM_HYBRID_KNOWN_USER_SCORE_CENTERING_WEIGHT = 0.5

TRAINING_ITEM_FREQUENCY_WEIGHTING = "inverse_sqrt"
TRAINING_ITEM_FREQUENCY_MULTIPLIER_MIN = 0.25
TRAINING_USER_ACTIVITY_WEIGHTING = "cap_at_median"
TRAINING_USER_ACTIVITY_MULTIPLIER_MIN = 0.05

PROFILE_ACTION_STRENGTHS = {
    "favorite": 0.5,
    "watched": 0.75,
    "saved": 1.0,
    "pinned": 1.0,
    "passed": 1.0,
}
PROFILE_FEATURE_TOP_K = {
    "genre": 6,
    "keyword": 30,
    "actor": 30,
    "director": 12,
    "theme": 12,
    "mood": 10,
}
SHORT_TERM_FEATURE_TOP_K = {
    "genre": 4,
    "keyword": 16,
    "actor": 12,
    "director": 8,
    "theme": 8,
    "mood": 8,
}
PROFILE_FEATURE_SCORE_CAPS = {
    "genre": 4.0,
    "keyword": 3.0,
    "actor": 2.0,
    "director": 3.0,
    "theme": 3.0,
    "mood": 3.0,
}
PROFILE_EVIDENCE_PER_FEATURE = 8
SHORT_TERM_MAX_ACTIONS = 50
SHORT_TERM_WINDOW_DAYS = 30
SHORT_TERM_HALF_LIFE_DAYS = 14.0

TRAINING_ACTION_WEIGHTS = {
    "favorite": 1.0,
    "watched": 1.5,
    "saved": 2.0,
    "pinned": 2.0,
}
TRAINING_ACTION_PRIORITY = ("pinned", "saved", "watched", "favorite")
TRAINING_OVERLAP_CONFIDENCE_BONUS = 0.15
TRAINING_MAX_SAMPLE_WEIGHT = 2.3
TRAINING_RECENCY_HALF_LIFE_DAYS = {
    "favorite": None,
    "watched": 180.0,
    "saved": 365.0,
    "pinned": 365.0,
    "passed": 90.0,
}
TRAINING_RECENCY_MIN_MULTIPLIER = 0.05
TRAINING_MISSING_TIMESTAMP_MULTIPLIERS = {
    "favorite": 1.0,
    "watched": 0.25,
    "saved": 0.25,
    "pinned": 0.25,
    "passed": 0.25,
}
