ENGINE_NAME = "v3"
ENGINE_VERSION = "v3.0.0"
SERVING_BUNDLE_FORMAT_VERSION = 1
SERVING_BUNDLE_ROOT = "assets/ml_models/v3"
POLICY_CONFIG_VERSION = "v3-policy-s8-v3"

CANDIDATE_POOL_SIZE = 100
CANDIDATE_RESERVE_SIZE = 50
CANDIDATE_STORAGE_SIZE = CANDIDATE_POOL_SIZE + CANDIDATE_RESERVE_SIZE
MAX_PAGE_SIZE = 100
CANDIDATE_USER_BLOCK_SIZE = 32
CANDIDATE_ITEM_BLOCK_SIZE = 8_192
CANDIDATE_CHECKPOINT_USER_COUNT = 1_024
CANDIDATE_SNAPSHOT_FORMAT_VERSION = 1
SHORT_TERM_RETRIEVAL_LIMIT = 100
SHORT_TERM_CANDIDATE_CACHE_FORMAT_VERSION = 3
SHORT_TERM_CANDIDATE_CACHE_TTL_SECONDS = 60 * 60 * 6
SHORT_TERM_CANDIDATE_CACHE_TTL_JITTER_SECONDS = 60 * 30
SHORT_TERM_DRIFT_MAX_WEIGHT = 0.45
SHORT_TERM_CONTEXT_FLOOR_MIN_DRIFT = 0.60
SHORT_TERM_CONTEXT_FLOOR_MAX_RATIO = 0.25

# S8 serving policy defaults. These values are provisional and must be tuned by ablation.
POLICY_PERSONAL_COMPONENT_WEIGHT = 0.75
POLICY_ONTOLOGY_COMPONENT_WEIGHT = 0.25
POLICY_ONTOLOGY_SHORT_TERM_MULTIPLIER = 0.5
POLICY_BLOCKED_MOVIE_STATUSES = frozenset({"취소됨", "Canceled"})
POLICY_OTT_BONUS_MAX = 0.04
POLICY_RECENCY_BONUS_MAX = 0.03
POLICY_RECENCY_WINDOW_DAYS = 365
POLICY_QUALITY_BONUS_MAX = 0.08
POLICY_QUALITY_VOTE_CONFIDENCE_PRIOR = 100.0
POLICY_QUALITY_POPULARITY_REFERENCE = 100.0
POLICY_NEGATIVE_MAX_BASE_RATIO = 0.30
POLICY_NEGATIVE_MAX_ABSOLUTE = 0.20
POLICY_NEGATIVE_CONFIDENCE_PAIR_COUNT = 3
POLICY_NEGATIVE_SHORT_TERM_MULTIPLIER = 1.25
POLICY_NEGATIVE_FEATURE_WEIGHTS = {
    "genre": 0.15,
    "keyword": 0.35,
    "actor": 0.30,
    "director": 0.45,
    "theme": 0.45,
    "mood": 0.35,
}
POLICY_MMR_SIMILARITY_PENALTY_MAX = 0.08
POLICY_REPETITION_PENALTY_MAX = 0.06
COLD_START_FEATURE_ONLY_MODEL_WEIGHT = 0.30
COLD_START_GENRE_ONLY_MODEL_WEIGHT = 0.15
COLD_START_OVERVIEW_SUPPORT_BONUS_MAX = 0.25
COLD_START_GENRE_ONLY_SEMANTIC_WEIGHT = 0.65
COLD_START_GENRE_ONLY_QUALITY_WEIGHT = 0.35
COLD_START_GENRE_COVERAGE_WEIGHT = 0.70
COLD_START_GENRE_SPECIFICITY_WEIGHT = 0.30
COLD_START_GENRE_ONLY_MIN_VOTE_COUNT = 1
COLD_START_GENRE_ONLY_TRUSTED_VOTE_COUNT = 20

ONTOLOGY_BUILD_BATCH_SIZE = 1_000
ONTOLOGY_BUILD_WORKER_COUNT = 4
ONTOLOGY_AGGREGATION_POLICY_VERSION = "bounded-union-v1"
ONTOLOGY_BUILD_WORK_MEM = "64MB"

ITEM_FEATURE_EXPORTER_VERSION = "v1"
USER_FEATURE_EXPORTER_VERSION = "v1"
USER_FEATURE_EXPLICIT_GENRE_WEIGHT = 1.0
USER_FEATURE_FAVORITE_DERIVED_WEIGHT = 0.5
ITEM_FEATURE_MIN_MOVIE_FREQUENCY = {
    "keyword": 5,
    "actor": 5,
    "director": 5,
}
ITEM_FEATURE_MAX_CATALOG_RATIO = {
    "keyword": 0.5,
}

LIGHTFM_IDENTITY_NO_COMPONENTS = 64
LIGHTFM_IDENTITY_LOSS = "warp"
LIGHTFM_IDENTITY_EPOCHS = 40
LIGHTFM_IDENTITY_LEARNING_RATE = 0.05
LIGHTFM_IDENTITY_USER_ALPHA = 1e-6
LIGHTFM_IDENTITY_ITEM_ALPHA = 1e-6
LIGHTFM_IDENTITY_MAX_SAMPLED = 10
LIGHTFM_IDENTITY_RANDOM_SEED = 42
LIGHTFM_IDENTITY_NUM_THREADS = 1

PROFILE_ACTION_STRENGTHS = {
    "favorite": 0.5,
    "watched": 0.75,
    "saved": 1.0,
    "pinned": 1.0,
    "passed": 1.0,
}
PROFILE_FEATURE_TOP_K = {
    "genre": 6,
    "keyword": 30,
    "actor": 30,
    "director": 12,
    "theme": 12,
    "mood": 10,
}
SHORT_TERM_FEATURE_TOP_K = {
    "genre": 4,
    "keyword": 16,
    "actor": 12,
    "director": 8,
    "theme": 8,
    "mood": 8,
}
PROFILE_FEATURE_SCORE_CAPS = {
    "genre": 4.0,
    "keyword": 3.0,
    "actor": 2.0,
    "director": 3.0,
    "theme": 3.0,
    "mood": 3.0,
}
PROFILE_EVIDENCE_PER_FEATURE = 8
SHORT_TERM_MAX_ACTIONS = 50
SHORT_TERM_WINDOW_DAYS = 30
SHORT_TERM_HALF_LIFE_DAYS = 14.0

TRAINING_ACTION_WEIGHTS = {
    "favorite": 1.0,
    "watched": 1.5,
    "saved": 2.0,
    "pinned": 2.0,
}
TRAINING_ACTION_PRIORITY = ("pinned", "saved", "watched", "favorite")
TRAINING_OVERLAP_CONFIDENCE_BONUS = 0.15
TRAINING_MAX_SAMPLE_WEIGHT = 2.3
TRAINING_RECENCY_BUCKETS = (
    (30, 1.0),
    (90, 0.8),
    (180, 0.6),
)
TRAINING_OLDER_RECENCY_MULTIPLIER = 0.4
TRAINING_MISSING_TIMESTAMP_MULTIPLIER = 1.0
